FROM rust:alpine3.16 AS rustbuilder

WORKDIR /app

ENV GRPC_HOST=0.0.0.0:50052

RUN apk upgrade --update-cache --available && \
	apk add npm gcc cmake make g++

RUN npm install @a11ywatch/protos

COPY . .

RUN cargo install --no-default-features --path .

FROM node:19.5-alpine

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD="true" \ 
	NODE_ENV="development" \
    GRPC_HOST_MAV="mav:50053"

RUN apk upgrade --update-cache --available && \
	apk add openssl

WORKDIR /usr/src/app

COPY package*.json ./
COPY --from=rustbuilder /usr/local/cargo/bin/health_client /usr/local/bin/health_client

RUN npm ci

COPY . .

EXPOSE 50052

CMD ["node_modules/ts-node-dev/lib/bin.js", "--no-experimental-fetch", "--transpile-only", "src/server.ts"]