FROM rust:alpine AS rustbuilder

WORKDIR /app

ENV GRPC_HOST=0.0.0.0:50053

RUN apk upgrade --update-cache --available && \
	apk add npm gcc cmake make g++

RUN npm i @a11ywatch/protos

COPY . .

RUN cargo install --no-default-features --path .

FROM node:19.6-alpine

WORKDIR /usr/src/app

COPY package*.json yarn.lock ./

RUN apk upgrade --update-cache --available && \
	apk add openssl && \
    rm -rf /var/cache/apk/*

RUN yarn install --frozen-lockfile

COPY . .
COPY --from=rustbuilder /usr/local/cargo/bin/health_client /usr/local/bin/health_client

EXPOSE 50053

CMD ["node_modules/ts-node-dev/lib/bin.js", "--no-experimental-fetch", "--transpile-only", "-r", "tsconfig-paths/register", "src/server.ts"]