version: 2.1
orbs:
  codecov: codecov/codecov@3.2.2
jobs:
  api:
    docker:
      - image: cimg/node:18.4.0
    environment:
      - NODE_OPTIONS: --no-experimental-fetch
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-v1-{{ .Branch }}-
            - node-v1-
      - run:
          command: npm ci && npm test
      - save_cache:
          paths:
            - ~/usr/local/lib/node_modules
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - codecov/upload:
          file: "./coverage/clover.xml"

workflows:
  build_and_test:
    jobs:
      - api
